version: "3"
services:
  seeTrue:
    container_name: SeeTrueImage
    image: theonlybeardedbeast/seetrue.api:latest
    restart: unless-stopped
    ports:
      - "9999:80"
    environment:
      SEETRUE_ALLOWED_HOSTS: http://localhost:3000,http://localhost:3001,http://192.168.64.2:9998
      SEETRUE_SIGNING_KEY: Uvz9WCdELTkqaZLVYgLHdzURl6YBe38t
      SEETRUE_SMTP_USER: service@mailhog.example
      SEETRUE_AUIDIENCES: http://localhost:5000
      SEETRUE_VERIFICATION_TOKEN_LIFETIME: 24
      SEETRUE_ISSUER: http://localhost:5000
      SEETRUE_REFRESH_TOKEN_LIFETIME: 336
      SEETRUE_API_KEY: SuperSecureApiKey
      SEETRUE_RECOVERY_MAX_FREQUENCY: 5
      SEETRUE_SMTP_HOST: 192.168.64.2
      SEETRUE_VALIDATE_AUDIENCE: true
      SEETRUE_SIGNUP_DISABLED: false
      SEETRUE_VALIDATE_ISSUER: true
      SEETRUE_TOKEN_LIFETIME: 3600
      SEETRUE_INVITE_ENABLED: true
      SEETRUE_SMTP_PASS: 12345678
      SEETRUE_ADMIN_ROLE: admin
      SEETRUE_SMTP_PORT: 1025
      SEETRUE_LANGUAGES: en
      SEETRUE_MAILFROM_EMAIL: seetrue@seetrue.st
      SEETRUE_MAILFROM_NAME: "SeeTrue"
    networks:
      - app
    depends_on:
      - db
  seeTrueAdmin:
    image: theonlybeardedbeast/seetrue.admin:latest
    restart: unless-stopped
    ports:
      - "9998:80"
    networks:
      - app
    depends_on:
      - db
  mailhog:
    image: mailhog/mailhog
    networks:
      - app
    ports:
      - "1025:1025"
      - "8025:8025"
networks:
  app:
    name: seetruenetwork
    driver: bridge
