FROM node:16.13.1 as build
WORKDIR /app
COPY . .
WORKDIR /app

RUN yarn

ENV GENERATE_SOURCEMAP=false

RUN yarn build

FROM nginx:1.21.6-alpine
COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]