name: ci

on:
  push:
    tags:        
      - v**
    branches:
      - "master"

jobs:
  seetrueapi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: api.dockerfile
          push: true
          tags: theonlybeardedbeast/seetrue.api:latest,theonlybeardedbeast/seetrue.api:${{ env.TAG }}
  seetrueadmin:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:SeeTrue.Admin"
          push: true
          tags: theonlybeardedbeast/seetrue.admin:latest,theonlybeardedbeast/seetrue.admin:${{ env.TAG }}